import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/db';
import { Testimonial } from '@/lib/models/Testimonial';

export async function GET(req: Request) { try { await connectToDatabase(); const all = new URL(req.url).searchParams.get('all') === 'true'; const testimonials = await Testimonial.find(all ? {} : { status: 'Approved' }).sort({ createdAt: -1 }).lean(); return NextResponse.json({ success: true, testimonials }); } catch (error: any) { return NextResponse.json({ success: false, message: error.message }, { status: 500 }); } }
export async function POST(req: Request) { try { const { name, email, phone, role, company, content, rating } = await req.json(); if (!name || !email || !phone || !content || !rating) return NextResponse.json({ success: false, message: 'Name, email, phone, rating, and review are required.' }, { status: 400 }); await connectToDatabase(); const testimonial = await Testimonial.create({ name, email, phone, role, company, content, rating: Number(rating), status: 'Pending' }); return NextResponse.json({ success: true, testimonial, message: 'Thank you. Your review will appear after admin approval.' }); } catch (error: any) { return NextResponse.json({ success: false, message: error.message }, { status: 500 }); } }
export async function PATCH(req: Request) { try { const { id, status } = await req.json(); await connectToDatabase(); const testimonial = await Testimonial.findByIdAndUpdate(id, { status }, { new: true }); return NextResponse.json({ success: true, testimonial }); } catch (error: any) { return NextResponse.json({ success: false, message: error.message }, { status: 500 }); } }
export async function PUT(req: Request) { try { const { id, name, email, phone, role, company, content, rating } = await req.json(); await connectToDatabase(); const testimonial = await Testimonial.findByIdAndUpdate(id, { name, email, phone, role, company, content, rating: Number(rating) }, { new: true }); return NextResponse.json({ success: true, testimonial }); } catch (error: any) { return NextResponse.json({ success: false, message: error.message }, { status: 500 }); } }
export async function DELETE(req: Request) { try { const id = new URL(req.url).searchParams.get('id'); await connectToDatabase(); await Testimonial.findByIdAndDelete(id); return NextResponse.json({ success: true }); } catch (error: any) { return NextResponse.json({ success: false, message: error.message }, { status: 500 }); } }
