'use client';
import { useEffect, useState } from 'react';
import AdminSidebar from '@/components/AdminSidebar';
import { CheckCircle2, Star, Trash2 } from 'lucide-react';

export default function ReviewsPage() {
  const [reviews, setReviews] = useState<any[]>([]);
  const load = () => fetch('/api/testimonials?all=true').then((r) => r.json()).then((data) => { if (data.success) setReviews(data.testimonials); });
  useEffect(() => { load(); const timer = setInterval(load, 10000); return () => clearInterval(timer); }, []);
  const approve = async (id: string) => { const r = await fetch('/api/testimonials', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status: 'Approved' }) }); const data = await r.json(); if (data.success) setReviews((all) => all.map((item) => item._id === id ? data.testimonial : item)); };
  const remove = async (id: string) => { if (!confirm('Delete this review permanently?')) return; await fetch(`/api/testimonials?id=${id}`, { method: 'DELETE' }); setReviews((all) => all.filter((item) => item._id !== id)); };
  return <div className="flex min-h-screen theme-app-bg font-sans"><AdminSidebar /><main className="flex-1 p-6 sm:p-8 space-y-6 overflow-y-auto"><div className="pb-4 border-b border-slate-200 dark:border-slate-800"><h1 className="text-2xl font-bold theme-app-heading flex gap-2 items-center"><Star className="w-6 h-6 text-[#F5C623]" /> Review Moderation</h1><p className="text-xs theme-app-body mt-1">Approve reviews to publish them on the Home page, or delete unwanted submissions.</p></div><div className="space-y-4">{reviews.length === 0 ? <p className="text-center py-10 text-xs theme-app-body">No submitted reviews yet.</p> : reviews.map((review) => <article key={review._id} className="theme-app-card border border-slate-200 dark:border-slate-800 rounded-2xl p-5"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><div className="flex text-[#F5C623]">{Array.from({ length: review.rating }).map((_, index) => <Star key={index} className="w-4 h-4 fill-current" />)}</div><h2 className="font-bold theme-app-heading mt-2">{review.name}</h2><p className="text-xs theme-app-body">{review.role}{review.company ? ` · ${review.company}` : ''}</p><p className="text-sm theme-app-body mt-3">“{review.content}”</p></div><div className="flex items-start gap-2"><span className={`px-2 py-1 text-[10px] font-bold rounded-full ${review.status === 'Approved' ? 'text-emerald-500 bg-emerald-500/10' : 'text-amber-500 bg-amber-500/10'}`}>{review.status}</span>{review.status !== 'Approved' && <button onClick={() => approve(review._id)} className="p-2 rounded-lg text-emerald-500 hover:bg-emerald-500/10" title="Approve"><CheckCircle2 className="w-5 h-5" /></button>}<button onClick={() => remove(review._id)} className="p-2 rounded-lg text-rose-500 hover:bg-rose-500/10" title="Delete"><Trash2 className="w-5 h-5" /></button></div></div></article>)}</div></main></div>;
}
